name: WebOp
main: me.jayfella.webop.WebOpPlugin
version: ${project.version}
author: jayfella & FabioZumbi12
api-version: 1.13
softdepend: [ "Essentials", "Vault" ]
commands:
  WebOp:
    description: "Main command for WebOp."
    aliases: [webop, wop]
    permission: "webop.reload"